config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications
  get 'home/index'
  devise_for :users


  root to: 'home#index'



  resources :publications do
    member do
      post 'like'
      post 'dislike'
    end
    resources :comments, only: [:index, :create, :destroy] #repasar dependencias de rutas
    resources :reactions, only: [:create, :destroy]
  end

  resources :publications do
    resources :comments, only: [:new, :create]  
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  validates :texto, presence: true
  validates :fecha_publicacion, presence: true
  validates :user_id, inclusion: { in: [nil, 2] }
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  enum reaction_type: {
    no_me_gusta: 0,
    me_gusta: 1
  }

  


  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[  show edit update destroy ]
  before_action :set_publication
  # GET /comments or /comments.json
  def index
    @publication = Publication.find(params[:publication_id])
    @comments = @publication.comments
    
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment = @publication.comments.build
  end

    
  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @publication = Publication.find(params[:publication_id])
    @comment = @publication.comments.build(comment_params)

    if current_user
      @comment.user_id = current_user.id
    else
      # Si el usuario no está logueado, establece user_id = 2 (usuario anónimo)
      @comment.user_id = 2
    end

    puts "Comment User ID: #{@comment.user_id}"
  
    if @comment.save
      redirect_to @publication, notice: 'Comentario creado exitosamente.'
    else
      render :new
    end
  end
  

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:texto, :fecha_publicacion, :user_id, :publication_id)
    end

    def set_publication
      @publication = Publication.find(params[:publication_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[create show index new]
  # GET /publications or /publications.json

  def like
    @publication = Publication.find(params[:id])
    @reaction = Reaction.new(user: current_user, publication: @publication, tipo: 1)

    if @reaction.save
      redirect_to @publication, notice: "Me gusta registrado exitosamente."
    else
      redirect_to @publication, notice: "Error al registrar el me gusta."
    end
  end

  def dislike
    @publication = Publication.find(params[:id])
    @reaction = Reaction.new(user: current_user, publication: @publication, tipo: 0)

    if @reaction.save
      redirect_to @publication, notice: "No me gusta registrado exitosamente."
    else
      redirect_to @publication, notice: "Error al registrar el no me gusta."
    end
  end


  def index
    @publications = Publication.all

  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comment = Comment.new
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
   
  @publication = Publication.new(publication_params)

 
  @publication.user_id = current_user&.id


    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:titulo, :contenido, :fecha_publicacion, :ubicacion, :user_id)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    
    def create
      @publication = Publication.find(params[:publication_id])
      reaction_type = params[:reaction_type].to_sym
      @reaction = Reaction.new(publication: @publication, reaction_type: reaction_type)
  
      if user_signed_in?
        @reaction.user = current_user
      else
        @reaction.user_id = nil
      end
  
      if @reaction.save
        redirect_to @publication, notice: 'La reacción se agregó correctamente.'
      else
        redirect_to @publication, alert: 'No se pudo agregar la reacción.'
      end
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Texto:</strong>
    <%= comment.texto %>
  </p>

  <p>
    <strong>Fecha publicacion:</strong>
    <%= comment.fecha_publicacion %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Publication:</strong>
    <%= comment.publication_id %>

  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :texto, style: "display: block" %>
    <%= form.text_area :texto %>
  </div>

  <div>
    <%= form.label :fecha_publicacion, style: "display: block" %>
    <%= form.datetime_field :fecha_publicacion %>
  </div>

  <% unless current_user %>
    <%= form.hidden_field :user_id, value: 2 %>
  <% end %>

  <%= form.hidden_field :publication_id, value: @publication.id %>




  <div>
    <%= form.submit "Ingresar Comentario" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<div class="container">

  <p style="color: green"><%= notice %></p>

  <h1>Comments</h1>

  <div id="comments">
    <% @comments.each do |comment| %>
      <%= render comment %>
      <p>
        <%= link_to "Detalle de comentario", comment , class:"btn btn-primary"  %>
      </p>
    <% end %>
  </div>

  <%= link_to "New comment", new_publication_comment_path(@publication), class:"btn btn-primary" %>


</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>


<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="container pt-3">

<h1>Sitio Dedicado a <span class="text-danger">Verdaderos</span> Amantes de los Gatos</h1><br>
<p class="fs-3">Este proyecto fue constituido el 2020 con el afan<br>
de rescatar todos aquellos momentos importantes que <br>hemos
vivido junto a nuestras mascotas estos ultimos<br> tiempos
de crisis, no solamente social sino que post-pandemico</p>
<p>Todos los derechos reservados &commat; Desafio047G2</p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazyforcats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>  
  <p class="notice"><%= notice %></p> 
  <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/f8924afd89.js" crossorigin="anonymous"></script>  
    
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :contenido, style: "display: block" %>
    <%= form.text_area :contenido %>
  </div>

  <div>
    <%= form.label :fecha_publicacion, style: "display: block" %>
    <%= form.datetime_field :fecha_publicacion %>
  </div>

  <div>
    <%= form.label :ubicacion, style: "display: block" %>
    <%= form.text_field :ubicacion %>
  </div>

  <% if user_signed_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  <% else %>
    <%= form.hidden_field :user_id, value: nil %>
  <% end %>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p class="fs-5">
    <strong>Titulo:</strong>
    <strong><%= publication.titulo %></strong>
  </p>

  <p>
    <strong>Contenido:</strong>
    <%= publication.contenido %>
  </p>

  <p>
    <strong>Fecha publicacion:</strong>
    <%= publication.fecha_publicacion %>
  </p>

  <p>
    <strong>Ubicacion:</strong>
    <%= publication.ubicacion %>
  </p>

  <p>

    <strong>User:</strong>
        <% if publication.user_id.nil? %>
          <%= "Anónimo" %>
        <% else %>
         <strong class="text-success"><%= publication.user.email %></strong>
         <% end %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">

  <h2 class="my-4">Publicaciones de Crazy 4 Cats</h2>

  <div id="publications" class="familia_publication">
    <% @publications.each do |publication| %>
      <%= render publication %>
      <p class="my-4">
      <%= link_to "Mostrar Publicacion", publication, class: "btn btn-secondary" %>



        
        <div class="btn-group" role="group" aria-label="Reactions">

        <%= button_to like_publication_path(publication), method: :post, class: "btn btn-primary mx-3" do %>
          <i class="fa fa-heart"></i><%= publication.reactions.where(tipo: 1).count %>
        <% end %>

        </div>


        <div class="btn-group" role="group" aria-label="Reactions">
        <%= button_to dislike_publication_path(publication), method: :post, class: "btn btn-danger" do %>
          <i class="fa-solid fa-heart-crack"></i><%= publication.reactions.where(tipo: 0).count %>
          <% end %>
        </div>

        </p>
    <% end %>
  </div>

</div>

<%= link_to "New publication", new_publication_path, class: "btn btn-primary mx-4 my-5" %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<% if user_signed_in? %>
  <%= render "form", publication: @publication, current_user: current_user %>
<% else %>
  <%= render "form", publication: @publication, current_user: nil %>
<% end %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @publication %>

  <div>
    <%= link_to "Editar Publicacion", edit_publication_path(@publication), class: "btn btn-secondary btn-sm" %> |


    <%= link_to "Volver a Publicaciones", publications_path, class: "btn btn-secondary btn-sm" %> 

    <%= button_to "Eliminar Publicacion", @publication, method: :delete, class: "btn btn-danger btn-sm my-3" %> 
  </div>

  <div>
  <%= link_to "detales de  comentarios", publication_comments_path(@publication) , class: "btn btn-success btn-sm my-3" %>
  </div>



  <div>
    <h5>Comentarios</h5>
    <% @publication.comments.each do |comment| %>
      <p><strong><%= comment.user_id %>:</strong> <%= comment.texto %></p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
  <%= link_to root_path, class: "navbar-brand letra_especial fs-2 text-light letra_especial" do %>
    CrazyForCats. <b class="text-warning fs-1">&grave;</b>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Publicaciones", publications_path, class: "nav-link" %>

        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if user_signed_in? %>
          <i class="fa-solid fa-user-pen fs-4 mx-2"></i> <%= current_user.email %>
          <% else %>
            Registrate o conectate
          <% end %>
          </a>
         
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
          <% else %>
          <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
          <% end %>

          </ul>
        </li>

        
      </ul>
    </div>
  </div>
</nav>